### ISSUE TITLE
Building Debian 10 package with pbuilder fails

### ISSUE THREAD

**Issue by SwampRabbit** [adoptware/pinball#12]
Hello,

I am having an issue trying to package for Debian 10 with pbuilder.

I receive the following:
```
configure.ac:14: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:14: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:7: error: required file 'config.h.in' not found
addon/Makefile.am:8: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
base/Makefile.am:8: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
data/professor/Makefile.am:10: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
data/tux/Makefile.am:11: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
test/Makefile.am:9: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
autoreconf: automake failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
make: *** [debian/rules:25: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

```
Thank you for your time.

**Comment by SwampRabbit** [comment]
I just attempted with sbuild also and it fails with the same warnings and error.

I looked for a config.h.in but cannot find the file, I see all the references to it, but no file is created.

**Comment by rzr** [comment]
hi, are you trying to build the master branch ?

**Comment by SwampRabbit** [comment]
Yes, the only thing I can think of is I changed the debhelper from 5 to 10.
version 5 is the minimum allowed right now, i can attempt a build withe version 5 set though

**Comment by rzr** [comment]
Are you involved into debian ? 

I am looking for sponsorship for :
https://mentors.debian.net/packages/uploader/rzr@users.sf.net

**Comment by SwampRabbit** [comment]
Sorry, I am not a "Debian" maintainer, I am a package maintainer for MX Linux (a fork of Debian).

**Comment by rzr** [comment]
hi I plan to release a version for debian soon

are you able to build this branch:

https://github.com/rzr/pinball/tree/next/devel/snapshot/master

**Comment by SwampRabbit** [comment]
Philippe,

I can try to build it tomorrow at some point and let you know.

Thank you for reaching back out, we (MX Linux) had a few users interested
in it.

Josh

**Comment by rzr** [comment]
ok great!

feel free to test master branch, 

I plan to release a new version after aug 15 ?

@sergiomb2  Please can you suggest a version number I dont want to add any ambiguity with your releases

then I'll upgrade sdl2 for 0.2.0

Meanwhile please forkers try to rebase on master branch and submit patches individually as new PR,
I'll keep sf.net tree sync with github.

Thanks

**Comment by sergiomb2** [comment]
I did version 0.3.4 , but maybe I'd suggest 0.4.0

**Comment by rzr** [comment]
yea I thought about 0.4.0 for sdl2  not 0.2.0 
for sdl1.2 maybe 0.3.5 , but  patches are not ported yet any ones to suggests ?

**Comment by sergiomb2** [comment]
OK , I will try review something this evening

**Comment by sergiomb2** [comment]
git pull 
fatal: refusing to merge unrelated histories

you cleaned all history ? why ? now nothing can be merged .

**Comment by rzr** [comment]
yes it was all messed up
some attributions were missing 
please try to rebase.

gettex patches for i10n would be welcome

**Comment by SwampRabbit** [comment]
@rzr 

I was able to build both amd64 and i386 in a pbuilder schroot without problems.

I tested the i386 build because that is the VM I had up already.
It worked well, sound worked in the VM nicely too.

One note, it seems the version number is being appended in the debian/changelog a second time.  (0.0.3.1+90+g672bc8fa-0.3.1+90+g672bc8fa)

I don't know if you're automating it being updated via the dch command?
If you only update this file for releases, us package maintainers can handle updating it.

**Comment by sergiomb2** [comment]
> yes it was all messed up
> some attributions were missing
> please try to rebase.
> 
> gettex patches for i10n would be welcome

also IMHO packaging stuff should not be in this repo . 
I will try recover history with my old git clone , try extract the differences since https://github.com/sergiomb2/pinball/commit/0ca7f5cb0cd870f3799542985754bf9e2aa98286 that you made

**Comment by rzr** [comment]
yes this file is generated , it shouldn't be in master branch.

BTW I made scripts to create bootable images, I can share an image for i386 it's about 400M and boots to table in 10secs on recent hardware.

Would you @SwampRabbit  be interested to do try to generate MXLinux images from scratch with those scripts i am currently developing in this branch:

https://github.com/rzr/pinball/tree/sandbox/rzr/devel/master/extra

**Comment by SwampRabbit** [comment]
@sergiomb2 I don't think it matters where the "packaging stuff" is honestly, the debian folder and .spec files can be anywhere or at least build depends and runtime depends listed in the README or wiki.  For Debian, actual control and rule files from the developers just help save time.  Package maintainers can make them from scratch, but we may have a lot of questions.

I'd recommend just not updating the debian/changelog, let the package maintainers do that, the rest shouldn't change that often.  But without at least the control, rules, and copyright files... it extends the time to package by a lot.  Especially when we have to package 100 applications that don't give us anything except a make file.

@rzr I can look at it for sure, sounds interesting for sure!

**Comment by sergiomb2** [comment]
Hi,
I only continue do something , if we recreate the same tree again , I checked git on sourceforge.net and it is also a complete chaos  .
I may try use the old tree and commit one diff with all that is new .
Thank you

**Comment by rzr** [comment]
well i can assist you how to rebase 
you need to do something like 
git remote add upstream https://sf.net/.../pinball.git
git fetch --all
git rebase -i upstream/master

then you need to fix conflict on 1st patch and open PR  
and we keep going

**Comment by rzr** [comment]
Hi please can you try to rebuild debian/master branch ?

and then
 https://github.com/adoptware/pinball/releases/tag/0.3.20201218

**Comment by rzr** [comment]
Have you checked latest release ?

Note to self regarding debian packaging:

https://bugs.debian.org/567033
