### ISSUE TITLE
Document Source/How Built for Windows/Allegro

### ISSUE THREAD

**Issue by dosxga** [adoptware/pinball#40]
Document Source How Built for Windows? or what do the build directories look like? its not documented in build.md

Allegro from pinball-0.3.20230219 at https://master.dl.sourceforge.net/project/pinball/pinball/pinball-0.3.20230219/pinball-0.3.20230219.tar.gz
and https://sourceforge.net/projects/pinball/files/pinball/pinball-0.3.20230219/
other libraries used from pinball-test.zip
zlib
How compile?  similiar to build.md for linux?  not seeing where source is for allegro build
allegro

What Libraries or compilers used for dev environment?
What Libraries or compilers used for runtime environments?
compilier used; will keep trying
also trying Emercardero DevC++ 6.3

**Comment by dosxga** [comment]
Update: Found old info in the Source forge website, https://sourceforge.net/p/pinball/patches/search/?q=%21status%3Awont-fix+%26%26+%21status%3Aclosed&sort=mod_date_dt+desc
 back in 2005 people were using gcc4

**Comment by rzr** [comment]
Hi,

I used to build pinball for windows for:

http://rzr.online.fr/game.htm

IIRC I planed with mingw32 to produce win32 binaries from linux

**Comment by dosxga** [comment]
rzr thanks for the info;

all;
I found a Windows 32-bit binary on the SourceForge site, but cannot find source:  will post part of link: https://master.dl.sourceforge.net/project/pinball/pinball/pinball-0.3.0/pinball030-win.z...  will keep looking.  Please don't close thread until found or compiled.  Thanks.

**Comment by dosxga** [comment]
. Update 2:  update found source code with more install instructions in the pinball-30.tar.gz file labeled install in capital letters.  https://master.dl.sourceforge.net/project/pinball/pinball/pinball-0.3.0/pinball-0.3.0.tar.gz  
Someone may want to add a win32 binary section to the repository. Thanks All.   Closing

**Comment by rzr** [comment]
It would be nice to setup an docker file to create win32 binaries from sources
